<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.hazelcast.simudedupe</groupId>
    <artifactId>simu-dedup-tests</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <name>Simulator Dedup Tests</name>

    <properties>
        <maven.compiler.release>21</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <hazelcast.version>5.7.0</hazelcast.version>
        <hazelcast.simulator.version>2.0-SNAPSHOT</hazelcast.simulator.version>
        <log4j.version>2.25.3</log4j.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.hazelcast.simulator</groupId>
            <artifactId>driver-hazelcast4plus</artifactId>
            <version>${hazelcast.simulator.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.hazelcast.simulator</groupId>
            <artifactId>simulator</artifactId>
            <version>${hazelcast.simulator.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast</artifactId>
            <version>${hazelcast.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${log4j.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.0</version>
                <configuration>
                    <release>${maven.compiler.release}</release>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
